[package]
name = "swn_helper"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.7.2"
rand = "0.8.5"
serde_json = "1.0.128"
serde = {version = "1.0", features=["derive"]}
rfd = "0.14.1"

[build-dependencies]
slint-build = "1.7.2"
