import {ComboTableBox} from "combo_table_box.slint";

import {ColorPalette} from "styling.slint";

export component GridTableListView {
    in property <[[string]]> model;
    in property <int> hardpoint-count: 6;
    in property <int> column-limit: 2;
    in property <[string]> columns;
    in property <[length]> column_widths;

    //An item was selected. We'll pass back [index of item updated,index of item selected]
    callback item_selected(int,int);

    VerticalLayout {
        max-height: Math.ceil(hardpoint-count / column-limit) * 40px;
        Rectangle {
            max-height: Math.ceil(hardpoint-count / column-limit) * 40px;
            VerticalLayout {
                spacing: 5px;
                for indx in Math.ceil(hardpoint-count / column-limit): HorizontalLayout {
                    min-height: 30px;
                    spacing: 5px;
                    for inner in Math.min(hardpoint-count - indx * column-limit, column-limit): ComboTableBox {
                        column_widths: root.column_widths;
                        columns: root.columns;
                        choices: model;
                        selected(new-idx) => {
                            root.item_selected(indx * column-limit + inner,new-idx);
                        }
                    }
                }
            }
            if hardpoint-count == 0: Text {
                color: ColorPalette.accent-foreground;
                font-weight: 500;
                text: "No hardpoints to mount to";
            }
        }
    }
}




