export global Icons {
    out property <image> add: @image-url("../../assets/add.svg");
    out property <image> remove: @image-url("../../assets/remove.svg");
    out property <image> close: @image-url("../../assets/close.svg");
    out property <image> down: @image-url("../../assets/down.svg");
}

export global ColorPalette{
    out property <brush> background: #4f5e85;
    out property <brush> foreground:#4f759b;
    out property <brush> accent1:#728c91;
    out property <brush> accent2:#70a094;
    out property <brush> accent3:#6db39c;
    out property <brush> accent4:#92c9b1;
    out property <brush> accent-background:#5d5179;
    out property <brush> accent-foreground:#a2faa3;
    out property <brush> focus-border;
    out property <brush> state-hovered;
}

