
import { Button } from "std-widgets.slint";

export global MenuBarAdapter{
    callback menu-clicked;
    callback save-clicked;
    callback load-clicked;
    callback load-hulls-clicked;
}

export component MenuBar {
    HorizontalLayout {
        width: parent.width;
        height: 35px;
        spacing: 5px;
        Button {
            width: 75px;
            text: "Menu";
            clicked => {
                MenuBarAdapter.menu-clicked();
            }
        }
        Button {
            width: 75px;
            text: "Save";
            clicked => {
                MenuBarAdapter.save-clicked();
            }
        }
        load-menu := Button {
            width: 75px;
            text: "Load..";
            clicked => {sub-menu.show();}
        }
        
        sub-menu := PopupWindow{
            x:load-menu.x;
            y:load-menu.height + 2px;
            Rectangle {
                background: #4f5e85;
                border-radius: 2px;
                VerticalLayout {
                    spacing: 3px;
                    Button {
                        text: "Load Ships";
                        clicked => {
                            MenuBarAdapter.load-clicked();
                        }
                    }
                    Button {
                        text: "Load Hull Types";
                        clicked => {
                            MenuBarAdapter.load-hulls-clicked();
                        }
                    }
                }   
            }
        }
        
    }
    function menu-clicked(){
        MenuBarAdapter.menu-clicked();
    }
    function save-clicked(){
        MenuBarAdapter.save-clicked();
    }
    function load-clicked(){
        MenuBarAdapter.load-clicked();
    }
}